------------------------------------------------------------------
--cREAR USUARIO
------------------------------------------------------------------

DROP TABLE BANK CASCADE CONSTRAINTS;
DROP TABLE BRANCHES CASCADE CONSTRAINTS;
DROP TABLE BANK_BRANCH CASCADE CONSTRAINTS;
DROP TABLE ACCTS CASCACADE CONSTRAINTS;
DROP TABLE LOANS CASCADE CONSTRAINTS;
DROP TABLE A_C CASCADE CONSTRAINTS;
DROP TABLE L_C CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE BANK(
    Code INTEGER CONSTRAINT PK_CODE_BANK PRIMARY KEY,
    Name_ VARCHAR2(20) CONSTRAINT NN_NAME_BANK NOT NULL,
    Addr VARCHAR2(20) CONSTRAINT NN_ADDR_BANK NOT NULL, 
);

CREATE TABLE BRANCHES(
    Code INTEGER CONSTRAINT NN_,
    Name_ VARCHAR2(20) CONSTRAINT NN_NAME_BRANCHES NOT NULL,
    Addr VARCHAR2(20) CONSTRAINT NN_ADDR_BRANCHES NOT NULL, 
);
