REM consultas al libro Elmasri & Navathe
rem capitulo 4  SQL BASIC 

rem   Q0

SELECT Bdate, Address
FROM EMPLOYEE
WHERE Fname=‘John’ AND Minit=‘B’ AND Lname=‘Smith’;

rem Q1
SELECT Fname, Lname, Address
FROM EMPLOYEE, DEPARTMENT
WHERE Dname=‘Research’ AND Dnumber=Dno;

rem Q2:
SELECT Pnumber, Dnum, Lname, Address, Bdate
FROM PROJECT, DEPARTMENT, EMPLOYEE
WHERE Dnum=Dnumber AND Mgr_ssn=Ssn AND
Plocation=‘Stafford’;

rem Q1
SELECT EMPLOYEE.Fname, EMPLOYEE.LName,
EMPLOYEE.Address
FROM EMPLOYEE, DEPARTMENT
WHERE DEPARTMENT.DName=‘Research’ AND
DEPARTMENT.Dnumber=EMPLOYEE.Dno;

rem Q8:
/*
 SELECT E.Fname, E.Lname, S.Fname, S.Lname
FROM EMPLOYEE AS E, EMPLOYEE AS S
WHERE E.Super_ssn=S.Ssn;
*/

 SELECT E.Fname, E.Lname, S.Fname, S.Lname
FROM EMPLOYEE  E, EMPLOYEE S
WHERE E.Super_ssn=S.Ssn;


rem Q11: 
SELECT ALL Salary
FROM EMPLOYEE;

rem Q11A
 SELECT DISTINCT Salary
FROM EMPLOYEE;


rem Q4A:
 (SELECT DISTINCT Pnumber
FROM PROJECT, DEPARTMENT, EMPLOYEE
WHERE Dnum=Dnumber AND Mgr_ssn=Ssn
AND Lname=‘Smith’ )
UNION
( SELECT DISTINCT Pnumber
FROM PROJECT, WORKS_ON, EMPLOYEE
WHERE Pnumber=Pno AND Essn=Ssn
AND Lname=‘Smith’ );


rem 
rem  separando los subueries
SELECT DISTINCT Pnumber
FROM PROJECT, DEPARTMENT, EMPLOYEE
WHERE Dnum=Dnumber AND Mgr_ssn=Ssn
AND Lname=‘Smith’;
 rem segunda parte 
 SELECT DISTINCT Pnumber
FROM PROJECT, WORKS_ON, EMPLOYEE
WHERE Pnumber=Pno AND Essn=Ssn
AND Lname=‘Smith’;


rem Q12A.
 SELECT Fname, Lname
FROM EMPLOYEE
WHERE Address LIKE ‘%Houston,TX%’;

 SELECT Fname, Lname,address
FROM EMPLOYEE;

 SELECT Fname, Lname, address
FROM EMPLOYEE
WHERE Address LIKE ‘%Houston TX%’;




rem Q13
SELECT E.Fname, E.Lname, 1.1 * E.Salary AS Increased_sal
FROM EMPLOYEE  E, WORKS_ON  W, PROJECT  P
WHERE E.Ssn=W.Essn AND W.Pno=P.Pnumber AND
P.Pname=‘ProductX’;

rem Q14
 SELECT *
FROM EMPLOYEE
WHERE (Salary BETWEEN 30000 AND 40000) AND Dno = 5;

rem Q15 
Q15:

 SELECT D.Dname, E.Lname, E.Fname, P.Pname
FROM DEPARTMENT D, EMPLOYEE E, WORKS_ON W,PROJECT P
WHERE D.Dnumber= E.Dno AND E.Ssn= W.Essn AND
W.Pno= P.Pnumber
ORDER BY D.Dname, E.Lname, E.Fname;


REM DESPLIEGA TODAS LAS TABLAS 
SET COLSEP '|*|'
SET PAGESIZE 99
SET LINESIZE 180
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT * FROM DEP_LOCATIONS;
SELECT * FROM PROJECT;
SELECT * FROM WORKS_ON;
SELECT * FROM DEPENDENT;
REM 
REM -----------------------------------------
REM 
REM 
REM CONSULTEMOS EL DICCIONARIO DE DATOS 
REM 
REM DESPLEGUEMOS LOS ATRIBUTOS DE LAS TABLAS 
REM 

desc user_ind_columns
COL TABLE_NAME FORMAT A15
COL DATA_TYPE  FORMAT A15
COL DATA_SCALE FORMAT 999.99
COL NULLABLE   FORMAT A2
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH,
	DATA_PRECISION,DATA_SCALE,NULLABLE
	FROM USER_TAB_COLUMNS 
	WHERE TABLE_NAME IN ( 'EMPLOYEE', 'WORKS_ON','DEPARTMENT',
	'DEPT_LOCATIONS','PROJECT','DEPENDENT')
	ORDER BY 1,2;
	

REM DESPLEGUEMOS LOS OBJETOS DEL USUARIO 
REM 
COL OBJECT_NAME FORMAT A25
COL OBJECT__TYPE FORMAT A12
COL OBJECT_ID   FORMAT 99,999	
SELECT OBJECT_NAME, OBJECT_TYPE, OBJECT_ID
	FROM USER_OBJECTS
	WHERE OBJECT_TYPE IN ('TABLE','INDEX', 'VIEW')
	ORDER BY 2,1;

REM DESPLEGUEMOS LOS INDICES

COL INDEX_NAME FORMAT A20
COL TABLE_NAME FORMAT A30
COL COLUMN_NAME FORMAT A15
COL COLUMN_POSITION FORMAT 999
COL COLUMN_LENGTH   FORMAT 999
select index_name, table_name,column_name, column_position, column_length
	char_length
	from user_ind_columns
	where table_name in ( 'EMPLOYEE', 'WORKS_ON','DEPARTMENT',
	'DEPT_LOCATIONS','PROJECT','DEPENDENT');
	
	select table_name from dict
	where table_name LIKE  '%ROLE%' OR
	       TABLE_NAME LIKE '%PRIVS%';

SELECT * FROM SESSION_PRIVS;
SELECT * FROM SESSION_ROLES;

	





